table_config:
  name: "tbl_coeres_painel_anomes_v1_gold"
  database: "database_w1"
  workgroup: "workspace"
  partitions:
    - name: "year"
      type: "string"
      description: "Ano de referência"
    - name: "month"
      type: "string"
      description: "Mês de referência (01-12)"
    - name: "canal"
      type: "string"
      description: "Canal de comunicação"
  
  security:
    forbidden_operations: ["DELETE", "INSERT", "ALTER", "DROP", "TRUNCATE", "UPDATE"]
    maximum_rows: 100000

  query_examples:
    - description: "Consulta básica com filtro de partições"
      sql: |
        SELECT produto, AVG(potencial) as media_potencial
        FROM tbl_coeres_painel_anomes_v1_gold
        WHERE year = 2024
          AND month = 5
          AND canal = 'VAI'
        GROUP BY produto
        LIMIT 100
    
    - description: "Consulta com filtro de valores ignorados"
      sql: |
        SELECT canal, COUNT(*) as total
        FROM tbl_coeres_painel_anomes_v1_gold
        WHERE year = 2023
          AND month BETWEEN 1 AND 6
          AND produto NOT IN ('TESTE', 'DEV')
        GROUP BY canal
    
    - description: "Consulta de potencial geral"
      sql: |
        SELECT 
        canal
        ,COUNT(DISTINCT potencial = 1 THEN cnpj END) as potencial
        FROM tbl_coeres_painel_anomes_v1_gold
        WHERE year='2025' and month ='01' 
        GROUP BY 1

    - description: "Consulta geral de funil"
      sql: |
        SELECT 
        canal
        ,COUNT(DISTINCT potencial = 1 THEN cnpj END) as potencial
        ,COUNT(DISTINCT visto = 1 THEN cnpj END) as visto
        ,COUNT(DISTINCT clique = 1 THEN cnpj END) as clique
        ,COUNT(DISTINCT atuado = 1 THEN cnpj END) as atuado
        ,COUNT(DISTINCT disponivel = 1 THEN cnpj END) as disponivel

        FROM tbl_coeres_painel_anomes_v1_gold
        WHERE year='2025' and month ='01'
        AND conta = 'CONTA ATIVA'
        GROUP BY 1

columns:
  - name: "cnpj"
    type: "bigint"
    description: "Campo unico para identificar o cliente que recebeu alguma camapnha"
    ignore_values: []

  - name: "produto"
    type: "string"
    description: "Tipo de produto financeiro"
    ignore_values: []
  
  - name: "abastecido"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente foi abastecido! Exemplo WHERE abastecido=1, COUNT(DISTINCT WHEN abastecido=1)"
  
  - name: "potencial"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente foi potencial! Exemplo WHERE potencial=1, COUNT(DISTINCT WHEN potencial=1)"  

  - name: "visto"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente visualizou a campanha! Exemplo WHERE visto=1, COUNT(DISTINCT WHEN visto=1)"  

  - name: "clique"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente clicou em uma campanha! Exemplo WHERE clique=1, COUNT(DISTINCT WHEN clique=1)"     

  - name: "atuado"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente clicou em uma campanha! Exemplo WHERE atuado=1, COUNT(DISTINCT WHEN atuado=1)"     

  - name: "disponivel"
    type: "int"
    description: "Campo numerico podendo ser 0 ou 1 para identificar se um cliente clicou em uma campanha! Exemplo WHERE disponivel=1, COUNT(DISTINCT WHEN disponivel=1)"     

  - name: "canal"
    type: "string"
    description: "Campo para identificar em qual canal foi disparado a campanha"

  - name: "metrica_engajamento"
    type: "double"
    description: "Índice de engajamento do cliente"


query_guidelines:
  - "Sempre usar partições year/month/canal como strings"
  - "Usar COUNT(DISTINCT CASE WHEN) para métricas binárias"
  - "Comparar conversões entre estágios do funil"
  - "Validar formato das datas (YYYY para year, MM para month)"