curiosidades:
- descricao: O nome Itaú vem do tupi-guarani e significa 'pedra preta' (Ita = pedra
    + U = preto ou escuro). Foi inspirado na cidade de Itaú de Minas (MG), onde o
    banco foi fundado.
  titulo: Significado do Nome
- descricao: O Itaú foi fundado em 1945, na cidade de Itaú de Minas (MG), e seu nome
    vem dessa cidade.
  titulo: Origem e Nome
- descricao: Em 2008, o Itaú se uniu ao Unibanco, formando o maior banco privado do
    Brasil e um dos maiores da América Latina.
  titulo: Fusão Histórica
- descricao: O Itaú tem operações em mais de 18 países, incluindo Estados Unidos,
    Argentina, Chile e até China.
  titulo: Presença Global
- descricao: Atualmente, o Itaú Unibanco é o maior banco privado do Brasil em ativos,
    superando seus concorrentes diretos como Bradesco e Santander.
  titulo: Maior Banco Privado do Brasil
- descricao: O Itaú foi pioneiro no Brasil ao lançar o Banco24Horas nos anos 1980
    e um dos primeiros a oferecer serviços bancários via internet.
  titulo: Primeiro Banco Digital
- descricao: O Itaú é um dos principais patrocinadores do futebol brasileiro, incluindo
    a Seleção Brasileira, além de apoiar esportes como tênis e ciclismo.
  titulo: Patrocínio Esportivo
- descricao: O laranja vibrante do banco foi escolhido para transmitir energia, inovação
    e jovialidade, sendo um dos logotipos mais reconhecidos do Brasil.
  titulo: O famoso 'Itaú Laranja'
- descricao: Em 2017, o Itaú comprou as operações de varejo do Citibank no Brasil,
    expandindo sua base de clientes de alta renda.
  titulo: Aquisição do Citibank
- descricao: O Itaú investe pesadamente em tecnologia e inteligência artificial, sendo
    um dos líderes no setor de fintechs e open banking no Brasil.
  titulo: Inovação Tecnológica
- descricao: O banco tem diversas iniciativas sustentáveis, incluindo metas para reduzir
    emissões de carbono, financiar projetos verdes e apoiar causas sociais.
  titulo: Compromisso com Sustentabilidade
- descricao: O Itaú mantém uma fundação dedicada a projetos educacionais e sociais
    para melhorar a educação pública no Brasil.
  titulo: Fundação Itaú Social
- descricao: O Itaú investe em cultura, apoiando projetos artísticos, exposições e
    literatura, além de manter um grande acervo digital gratuito.
  titulo: Itaú Cultural
- descricao: O Itaú Unibanco é o maior banco da América Latina em valor de mercado,
    superando concorrentes regionais.
  titulo: Maior banco da América Latina
- descricao: O Itaú frequentemente registra lucros bilionários trimestrais, sendo
    um dos bancos mais rentáveis do Brasil.
  titulo: Lucro Bilionário
- descricao: O Itaú já foi considerado a marca bancária mais valiosa do Brasil, de
    acordo com rankings internacionais.
  titulo: Banco Mais Valioso
- descricao: O Itaú criou o Iti, sua fintech de pagamentos e conta digital, para competir
    no mercado de bancos digitais.
  titulo: Conta Digital Iti
- descricao: O banco utiliza IA em atendimento ao cliente, análise de crédito e detecção
    de fraudes.
  titulo: Uso de Inteligência Artificial
- descricao: O aplicativo do Itaú é um dos mais bem avaliados no setor bancário brasileiro,
    oferecendo diversas funcionalidades para os clientes.
  titulo: App Itaú
- descricao: As ações do Itaú Unibanco são negociadas na Bolsa de Valores de Nova
    York (NYSE).
  titulo: Presença em Wall Street
- descricao: O banco mantém programas de incentivo para pequenos empreendedores e
    startups.
  titulo: Apoio ao Empreendedorismo
- descricao: O Itaú já patrocinou as Olimpíadas do Rio 2016, apoiando o evento e os
    atletas brasileiros.
  titulo: Presença no Esporte Olímpico
- descricao: Os clientes do Itaú podem personalizar seus cartões com imagens e cores
    preferidas.
  titulo: Cartões Personalizados
- descricao: O Itaú criou o segmento Personnalité para clientes de alta renda, oferecendo
    serviços exclusivos.
  titulo: Criação do Personnalité
- descricao: O Itaú mantém parcerias com universidades e oferece soluções financeiras
    para estudantes.
  titulo: Presença em Universidades
- descricao: O banco investe em fintechs e startups inovadoras através de seu fundo
    de venture capital.
  titulo: Investimentos em Startups
- descricao: O Itaú foi um dos primeiros bancos a oferecer cartões com pagamento por
    aproximação no Brasil.
  titulo: Cartões com Tecnologia Contactless
- descricao: O banco implementa várias camadas de segurança, incluindo biometria,
    token e reconhecimento facial em seus serviços digitais.
  titulo: Segurança Digital
- descricao: O Itaú patrocina programas de compartilhamento de bicicletas em diversas
    cidades do Brasil.
  titulo: Apoio a Mobilidade Urbana
